name: challene1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg_provider: ^1.0.6
  flutter_svg: ^2.0.9
  http: ^1.1.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  pie_chart: ^5.4.0
  fl_chart: ^0.64.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Bahij
      fonts:
        - asset: fonts/Bahij_TheSansArabic-Bold.ttf

  # fonts:
  #    - family: Lato
  #      fonts:
  #        - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
